# Plantilla de Pre Procesado

# Cómo importar las librerías


In [51]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importar el data set


In [52]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

# Tratamiento de los NAs

In [53]:
from sklearn.impute import SimpleImputer

In [54]:
imputer = SimpleImputer(missing_values = np.nan, strategy = "mean",verbose=0)
imputer = imputer.fit(X[:,1:3]) 
X[:, 1:3] = imputer.transform(X[:,1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Codificar datos categoricos

In [55]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [56]:
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                        
)

In [57]:
X = np.array(ct.fit_transform(X), dtype=np.int)
print(X)

[[    1     0     0    44 72000]
 [    0     0     1    27 48000]
 [    0     1     0    30 54000]
 [    0     0     1    38 61000]
 [    0     1     0    40 63777]
 [    1     0     0    35 58000]
 [    0     0     1    38 52000]
 [    1     0     0    48 79000]
 [    0     1     0    50 83000]
 [    1     0     0    37 67000]]


In [58]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Dividir el data set en conjunto de entrenamiento y conjunto de testing


In [62]:
from sklearn.model_selection import train_test_split

In [63]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Escalado de variables

In [64]:
from sklearn.preprocessing import StandardScaler

In [65]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [66]:
result_Xtrain = pd.DataFrame({'Column1': X_train[:, 0], 'Column2': X_train[:, 1],'Column3': X_train[:, 2], 'Column4': X_train[:, 3],'Column5': X_train[:, 4]})

In [70]:
display(result_Xtrain)

Column1   Column2   Column3   Column4   Column5
0     -1.0  2.645751 -0.774597  0.279780  0.123744
1      1.0 -0.377964 -0.774597 -0.236737  0.461767
2     -1.0 -0.377964  1.290994 -1.958462 -1.530925
3     -1.0 -0.377964  1.290994 -0.064565 -1.111411
4      1.0 -0.377964 -0.774597  1.657160  1.720310
5     -1.0 -0.377964  1.290994 -0.064565 -0.167504
6      1.0 -0.377964 -0.774597  0.968470  0.986160
7      1.0 -0.377964 -0.774597 -0.581082 -0.482140

In [71]:
result_X_test = pd.DataFrame({'Column1': X_test[:, 0], 'Column2': X_test[:, 1],'Column3': X_test[:, 2], 'Column4': X_test[:, 3],'Column5': X_test[:, 4]})

In [72]:
display(result_X_test)

Column1   Column2   Column3   Column4   Column5
0     -1.0  2.645751 -0.774597 -1.441944 -0.901654
1     -1.0  2.645751 -0.774597  2.001505  2.139824